# Generated by Django 4.2.1 on 2023-06-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='job',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_checkable',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vacancy_id',
        ),
        migrations.DeleteModel(
            name='JobVacancy',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.AddField(
            model_name='attempts',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv_management.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_management.test'),
        ),
    ]
