# Generated by Django 4.2.1 on 2023-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0003_test_remove_requirement_job_remove_attempts_vacancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='is_checkable',
            field=models.BooleanField(default=False),
        ),
    ]
