# Generated by Django 4.2.1 on 2023-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0004_attempts_is_checkable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempts',
            name='is_checkable',
        ),
        migrations.AddField(
            model_name='question',
            name='is_checkable',
            field=models.BooleanField(default=False),
        ),
    ]
